project:
  type: website
  title: "Causal Tutorial, AI4PH Summer Institute 2023"
  output-dir: docs
  render:
      - index.qmd
      - section1.qmd
      - section2.qmd
      - HTE.qmd

website:
  title: "Tutorial on Causal Inference Using Machine Learning Methods"
  site-url: https://kuan-liu.github.io/AI4PH2023_CausalWorkshop/
  repo-url: https://github.com/Kuan-Liu/AI4PH2023_CausalWorkshop/
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "[Kuan Liu](https://www.kuan-liu.com), University of Toronto @ 2023"
    background: "#77C5D5"

  navbar:
    background: primary
    right:
      - icon: github
        href: https://github.com/Kuan-Liu/AI4PH2023_CausalWorkshop

  sidebar:
    background: "#77C5D5"
    style: docked
    search: true
    contents:
        - index.qmd
        - section1.qmd
        - section2.qmd
        - HTE.qmd
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true

callout-appearance: simple

date: today
date-format: iso


